### ISSUE TITLE
Default-selected control in the signature-generating window is not `Continue`

### ISSUE THREAD

**Issue by KulaGGin** [kweatherman/sigmakerex#2] opened 2022-02-16 20:05 UTC
When trying to quickly find functions in another database, when I press `Ctrl+Alt+S`, I get this window:
![ida64_Gj0AqF3e3K](https://user-images.githubusercontent.com/16989713/154346207-ba734083-2c17-490d-9c25-52aa2b1a59cd.png)

Usually in this kind of cases, the default-selected control is `Ok`, or in this case it would be `Continue` button.

In SigMaker when I press `Ctrl+Alt+S` and then quickly press `Enter` on my mouse, instead of getting the signature, this Github repo gets opened.

I think it would make sense to make the `Continue` button to be the default-selected control, so when you already have set your preferred settings and you're generating multiple signatures in a row, you can quickly do it by just pressing `Ctrl+Alt+S > Enter`.

**Comment by kweatherman** [comment] 2022-02-16 23:20
Thanks for the report, fixed in v1.1.1

The IDA SDK is often more of an art than a science. 

According to the SDK: `A * after the button name means that this button will be the default:`
Which I had but it was clearly not working as intended.

Then there is an option for _STARTITEM_: `where number is a number of input field the cursor will stand on.`
So '0' should be the hyperlink button control and a little ambiguous here, '1' should probably be either the entire "Create signature" checkbox group; or maybe just the first item in group.
So reasonably you'd think that either '3' or '5' would be the "Continue" button. But actually from a process of elimination, it turns out "STARTITEM 1\n" does the trick..

**Closed by kweatherman** 2022-02-16 23:20 UTC
